main.py

Currently, the `--no-vis` option fails with:
```
Traceback (most recent call last):
File "main.py", line 248, in <module>
main()
File "main.py", line 244, in main
win = visdom_plot(viz, win, args.log_dir, args.env_name, args.algo)
UnboundLocalError: local variable 'viz' referenced before assignment
```

Fix conditional to enable --no-vis option to work properly

---

distributions.py

I believe this is a bug. Ran into it running the CNN policy on an environment with continuous actions. You have a number of values which are hardcoded (eg: layer sizes) when they should be based on the input/output size.

Fix layer size in DiagGaussian

---

envs.py

WrapPyTorch has sizes specific to atari envs baked in. Getting the shape from the wrapped environment allows it to work with other observation image sizes.

Made WrapPyTorch get obs space shape from env

---

envs.py

My environment is not atari but also has the color channels in the last dimension. This seems more generic.

Make WrapPyTorch apply to non-atari environments

---

kfac.py

Currently this operation is move to CPU every time due to a bug in pytorch. This bug now seems to be fixed in pytorch 0.3.0. 
https://github.com/pytorch/pytorch/releases

remove moving stats to cpu.

---

distributions.py

The current code uses implicit dimension choice for `softmax` and `log_softmax`, which have been deprecated. 
```
UserWarning: Implicit dimension choice for log_softmax has been deprecated. Change the call to include dim=X as an argument.
```

add explict dimension choice for softmax and log-softmax function

---

.gitignore
README.md
envs.py

This PR adds support for the DeepMind Control Suite tasks via dm_control2gym (https://github.com/martinseilair/dm_control2gym).
Use it by specifying an env name in the form `dm.<domain_name>.<task_name>`.

Add support for DeepMind Control Suite

---

algo/ppo.py

gru is inside self.actor_critic.base, but the earlier check was to see if gru was inside self.actor_critic.
This might have affected recurrent PPO runs till now. Data was not being generated from the recurrent_generator, so the data being fed at each time t would have been incoherent with the other times.
This fix addresses only PPO. Not certain that this does not exist in other algo implementations, but there isn't a straightforward gru check in those algo/kfac.py or algo/a2c_acktr.py.

ppo recurrent check fixed.

---

algo/kfac.py

If a model training with KFAC is resumed the algorithm tries to readd the split biases to a layer with a bias parameter. This PR solves this issue.

Apply SplitBiases in KFAC only once to a model

---

model.py
storage.py

Plot of current ppo implementation with a recurrent policy
Plot of same experiment with the bug fixed.
While fixing this bug doesn't seem to improve performance (on pong at least), it definitely improves stability.

Fixes bug in recurrent policy.  Issue #97

---

enjoy.py
main.py
utils.py

For consistency reasons and in order to make the code cleaner I suggest to move the `current_obs` function to `utils`. In general, I think it is good to avoid inline functions and code repetition as much as possible.

Extract update_current_obs function to utils

---

algo/a2c_acktr.py
algo/ppo.py
main.py
storage.py

This PR introduces two small changes:
1. Add the new `.to(device)` syntax to `RolloutStorage` and `main.py`.
2. Return the weighted value loss and distribution entropy from algorithms. This does not change the optimisation but a more accurate logging of these metrics. In particular if for example `value_loss_coef = 0.0`.

Introduce to device syntax

---

envs.py
main.py

In this PR I did some minor refactoring, in particular of the `VecPyTorchFrameStack ` class. I also added the `num_frame_stack ` parameter to the `make_vec_envs ` function. Although this is not used in `main.py`, I think it makes sense to keep all the code except from `main.py` (since this is the file that most users customize) as backwards compatible as possible.

Refactor VecPyTorchFrameStack

---

enjoy.py
envs.py
main.py
utils.py

This PR circumvents the "ugly" hack of adding a manual `obfilt` method by introducing a `VecNormalize` class with eval mode (in analogy to PyTorch model eval mode). In addition, it solves a previous bug in which the check whether the vector environment is a `VecNormalize` class is always false if no `VecPyTorchFrameStack` env is wrapped. (See `make_vec_envs` and the varying number of `.venv` calls necessary to get to the potential `VecNormalize` class.)
Also notice the change of `hasattr` to `getattr` for saving the `ob_rms` and the new `get_render_func` function. In general, I think there should be a better way to reach different environment wrappers but I am currently not aware of any.
@ikostrikov I did some testing of these changes but please double check with your usual testing …

Add VecNormalize with eval mode and fix previous bug

---

model.py

The currently recurrent policy implementation uses a `GRUCell` and thus a for-loop to evaluate each step in the rollout.  This PR changes the recurrent policy to use a `GRU` (which unfortunately breaks existing pre-trained models) and evaluates the sequence with as few `forward` calls as possible.
In order to reset the hidden state, the `masks` tensor is checked to see if any element has a zero for each step in the rollout (a zero in `masks` corresponds to at a done in the rollout).  If steps `t_1` and `t_2` have at least one done, then steps `t` such that `t_1 <= t < t_2` are run with one call to `forward`.
This results in a massive speed up whenever the number of steps with at least one done is significantly less than the rollout length.  In `PongNoFrameskip-v4` with PPO I see ~1000 FPS …

Faster recurrent policy evaluate actions

---

arguments.py
main.py
utils.py

This attempts to solve #31 
I've added a simple implementation of a linear schedule on the learning rate from an initial value down to 0.
This is mentioned in the ACKTR paper but was missing here.
There is now an argument for toggling it (off by default)
There will be more elegant solutions based on http://pytorch.org/docs/master/_modules/torch/optim/lr_scheduler.html#LambdaLR, but I had trouble implementing this because of an older version of pytorch (0.2).

Added linear schedule for learning rate

---

distributions.py
main.py
model.py

This PR adds four major changes:
1. Add the Bernoulli distribution as suggested in #44. For the mode I just used a 0.5 threshold. I am open for suggestions to improve this little hack.
2. Add the Bernoulli distribution to the `Policy` class.
3. Change https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/669181152ed6e781ff7a25f7f65dd3daf91de6da/distributions.py#L21 to take the argmax of the last (`-1`) dimension.
4. Currently, one has to modify the `Policy` class to use custom base functions other than the preimplemented `MLPBase` and `CNNBase`. The new `base` argument of the `Policy` class allows to inject custom models without any trouble.

Policy with custom base and Bernoulli distribution

---

main.py

- Fixed  a minor bug in the evaluation code
If the model is on a gpu, `eval_masks` would cause an error since it is not a `torch.cuda.FloatTensor` type.
Instead, it should just be like `torch.tensor(..., dtype=torch.float32, device=device)`.

Fixed minor bug in evaluation code

---

a2c_ppo_acktr/algo/gail.py

PyTorch v0.4.1 returns float32 on calling `torch.randint()` (see this: https://github.com/pytorch/pytorch/issues/14886).

Fix data type for torch v0.4.1

---

main.py

Set drop_last=True only if the dataset size is more than GAIL batch size (otherwise it just returns an empty dataloader). See example below:
```python
>>> from torch.utils.data.sampler import BatchSampler, SequentialSampler
>>> list(BatchSampler(SequentialSampler(range(10)), batch_size=11, drop_last=True))
[]
```

Fix GAIL expert dataloader

---

a2c_ppo_acktr/algo/gail.py
a2c_ppo_acktr/envs.py

`openai/baselines` has tensorflow and mujoco dependencies by default. Tensorflow installation is not necessary for scripts in this repo and mujoco is not very friendly to build. It might be quite desirable to remove these dependencies by using `stable_baselines3` as done in this PR.

replace baselines dependencies

---

a2c_ppo_acktr/envs.py
enjoy.py
evaluation.py
main.py

The problem occurs in an environment where **obs_rms** is used because the variable **self.ob_rms** in the **VecNormalize class** in the **envs.py**  is not the same as **self.obs_rms** in the (from stable_baselines3.common.vec_env.vec_normalize import  **VecNormalize as VecNormalize_** ).

ob_rms_to_obs_rms

---

README.md
requirements.txt

1. add h5py in requirement.txt
2. since pip install gym atari doesn't work, add conda install gym atari in readme

add h5py in requirement.txt and add conda intall atari in readme
